title Retrieve All Products

note over Client,Server: QueryParams: limit, skip, select, q
Client->Server: GET /api/v1/products
Server->DummyJsonApi: async getProducts()
Server<--DummyJsonApi: Response from Api
alt error fetching data 500
Client<--Server: Error Response
end
Client<--Server: OK Response